version: '3'
services:
  db:
    image: postgres:15
    container_name: ufc-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ufcdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ufc-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

  frontend:
    build:
      context: ./ufc-ranking-front
      dockerfile: Dockerfile
    container_name: ufc-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${BACKEND_URL}
    ports:
      - "3000:3000"
    env_file:
      - ./ufc-ranking-front/.env

volumes:
  pgdata: